apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra

  destination:
    name: in-cluster
    namespace: monitoring

  source:
    repoURL: https://github.com/Scouterna/j26-infra.git
    targetRevision: main
    path: k8s/app-manifest/monitoring

  sources:
    - repoURL: ghcr.io/prometheus-community/charts
      chart: kube-prometheus-stack
      targetRevision: "80.2.2"
      helm:
        releaseName: kps
        valueFiles:
          - $values/k8s/app-manifest/monitoring/helm-values.yaml
    - repoURL: https://grafana.github.io/helm-charts
      chart: loki
      targetRevision: "6.49.0"
      helm:
        releaseName: loki
        valueFiles:
          - $values/k8s/app-manifest/monitoring/loki-values.yaml
    - repoURL: https://grafana.github.io/helm-charts
      chart: alloy
      targetRevision: "1.5.0"
      helm:
        releaseName: alloy
        valueFiles:
          - $values/k8s/app-manifest/monitoring/alloy-values.yaml
    - repoURL: https://github.com/Scouterna/j26-infra.git
      targetRevision: main
      ref: values

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
