apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rollout-restart
subjects:
  - kind: ServiceAccount
    name: rollout-restart
    namespace: j26-infra
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rollout-restart-deployments
