apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader
  namespace: argocd
spec:
  project: common
  source:
    chart: stakater/reloader
    repoURL: https://stakater.github.io/stakater-charts
    targetRevision: 2.2.5
    helm:
      releaseName: reloader
  destination:
    server: "https://kubernetes.default.svc"
    namespace: reloader
