apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: j26-signupinfo-kv-csi
spec:
  provider: azure
  secretObjects:
  - secretName: j26-signupinfo-secrets
    type: Opaque
    data:
    # - key: SECRET_KEY_BASE
    #   objectName: j26-signupinfo-secret-key-base
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: 214abfc2-fa80-44b9-89c5-f78444a16816
    keyvaultName: kv-j26apps-shared-sdc
    tenantId: 317a47ba-fd32-41b8-8ebe-310a1adc9863
    objects:  |
      array:
        - |
          objectName: j26-signupinfo-secret-key-base
          objectType: secret
