apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/configmap.yaml
- ../../base/deployment.yaml
- ../../base/ingress.yaml
- ../../base/kustomization.yaml
- ../../base/secret-provider-class.yaml
- ../../base/service.yaml

patches:
- path: patch-deployment.yaml
  target:
    kind: Deployment
    name: j26-auth
- path: patch-configmap.yaml
  target:
    kind: ConfigMap
    name: j26-auth-config

images:
- name: ghcr.io/scouterna/j26-auth
  newTag: a23665d
