apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/*.yaml

patches:
  - path: patch-deployment.yaml
    target:
      kind: Deployment
      name: j26-auth
  - path: patch-configmap.yaml
    target:
      kind: ConfigMap
      name: j26-auth-config

images:
  - name: ghcr.io/scouterna/j26-auth
    newTag: a23665d
