apiVersion: apps/v1
kind: Deployment
metadata:
  name: j26-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: j26-app
  template:
    metadata:
      labels:
        app: j26-app
    spec:
      containers:
        - name: app
          image: ghcr.io/scouterna/j26-app:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: j26-app-config
