apiVersion: apps/v1
kind: Deployment
metadata:
  name: j26-booking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: j26-booking
  template:
    metadata:
      labels:
        app: j26-booking
    spec:
      containers:
        - name: app
          image: ghcr.io/scouterna/j26-booking:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: j26-booking-config
            - secretRef:
                name: j26-booking-secrets
            - secretRef:
                name: sc-postgresqla5566-secret
          volumeMounts:
            - name: secrets-store
              mountPath: "/mnt/secrets-store"
              readOnly: true
          env:
            - name: DATABASE_URL
              value: "postgresql://$(AZURE_POSTGRESQL_USERNAME):'$(AZURE_POSTGRESQL_PASSWORD)'@$(AZURE_POSTGRESQL_HOST):$(AZURE_POSTGRESQL_PORT)/$(AZURE_POSTGRESQL_DATABASE)?sslmode=require"
      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: j26-booking-kv-csi
