apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: j26-booking-kv-csi
spec:
  provider: azure
  secretObjects:
  - secretName: j26-booking-secrets
    type: Opaque
    data:
    - key: SECRET_KEY_BASE
      objectName: j26-booking-secret-key-base
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: 853b2477-d6de-4cba-9e21-08da51c35b8f
    keyvaultName: kv-j26-dev-sdc-k8s
    tenantId: 317a47ba-fd32-41b8-8ebe-310a1adc9863
    objects:  |
      array:
        - |
          objectName: j26-booking-secret-key-base
          objectType: secret
