assignments:
- groups: [j26-staff]
  if: |
    contains(fromJSON('["Funktionär"]'), fee.name) &&
    getAnswer('Internt', 'Allokering', 'Funktion')

- groups: [j26-planning-staff]
  if: |
    contains(fromJSON('["Funktionär"]'), fee.name) &&
    getAnswer('Internt', 'Allokering', 'Planeringsfunktionär') == 'checked'
