apiVersion: v1
kind: ConfigMap
metadata:
  name: j26-scoutid-sync-config
data:
  KEYCLOAK_CLIENT_ID: j26-group-import
  KEYCLOAK_PARENT_GROUP_ID: 9a9dbe39-e57f-4510-ae54-6d3b62aa14f3
  SCOUTNET_PROJECT_ID: "56033"
  SCOUTNET_FORM_ID: "46930"
