apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - cron-job.yaml
  - secret-provider-class.yaml

configMapGenerator:
  - name: j26-scoutid-sync-config-file
    files:
      - config.yml
