apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: j26-scoutid-sync-kv-csi
spec:
  provider: azure
  secretObjects:
  - secretName: j26-scoutid-sync-secrets
    type: Opaque
    data:
    - key: KEYCLOAK_CLIENT_SECRET
      objectName: scoutid-sync-keycloak-client-secret
    - key: SCOUTNET_MEMBERS_API_KEY
      objectName: scoutid-sync-scoutnet-members-api-key
    - key: SCOUTNET_QUESTIONS_API_KEY
      objectName: scoutid-sync-scoutnet-questions-api-key
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: 214abfc2-fa80-44b9-89c5-f78444a16816
    keyvaultName: kv-j26apps-shared-sdc
    tenantId: 317a47ba-fd32-41b8-8ebe-310a1adc9863
    objects:  |
      array:
        - |
          objectName: scoutid-sync-keycloak-client-secret
          objectType: secret
        - |
          objectName: scoutid-sync-scoutnet-members-api-key
          objectType: secret
        - |
          objectName: scoutid-sync-scoutnet-questions-api-key
          objectType: secret
