apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: disk-standardssd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
provisioner: disk.csi.azure.com
parameters:
  skuName: StandardSSD_LRS
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
