apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: echourl-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: echourl-app
  source:
    repoURL: https://github.com/Scouterna/j26-infra.git
    targetRevision: HEAD
    path: k8s/app-manifest/echourl-app
  destination:
    server: https://kubernetes.default.svc
    namespace: echourl-app
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
